spring.application.name=EurekaServer

#Port généralement utilisé pour le serveur eureka
server.port=8761
#Indique au microservice de ne pas s'auto référencer
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#Site web d'Eureka : http://localhost:8761/


#############
#Actuator
#############
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Active le endpoint logfile
management.endpoint.logfile.access=read_only
#Activer l'arrêt à distance
management.endpoint.shutdown.access=unrestricted
#Les 100 dernières requêtes recues
management.endpoint.httpexchanges.access=read_only
# Indique le fichier de log à exposer
logging.file.name=logs/app.log

##########
# Spring Boot Admin
#############
## Lien du serveur SpringBootAdmin
spring.boot.admin.client.url=http://localhost:8083/
##Envoi de l'adresse ip de la machine client au serveur
spring.boot.admin.client.instance.service-host-type=IP

