spring.application.name=AdminService

#Pas de port spécifique pour SpringBoot Admin
server.port=8083
#Page web disponible par défaut : http://localhost:8083
#Si on souhaite un autre lien :


#Très important, car cela viendra remplacer l'adresseIP dans l'URL avec le LoadBalancer
#Permet d'activer/désactiver les logs d'échec de recherche du EurekaServeur
logging.level.com.netflix.discovery=OFF
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Chaque microservice envera l'ip local de la machine qui l'hberge à Eureka
eureka.instance.hostname=localhost

#############
#Actuator
#############
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Active le endpoint logfile
management.endpoint.logfile.access=read_only
#Activer l'arrêt à distance
management.endpoint.shutdown.access=unrestricted
#Les 100 dernières requêtes recues
management.endpoint.httpexchanges.access=read_only
# Indique le fichier de log à exposer
logging.file.name=logs/app.log
