//Création
POST http://localhost:8081/movieEntities
Content-Type: application/json

{"title":"toto", "length":100}

###

//GET 1
GET http://localhost:8081/movieEntities/1
Content-Type: application/json
###

//Remplace
PUT http://localhost:8081/movieEntities/1
Content-Type: application/json

{"title":"blabla" , "length":200}
###

//Mise à jour partielle
PATCH http://localhost:8081/movieEntities/1
Content-Type: application/json

{"title":"toto"}
###

//GET All
GET http://localhost:8081/movieEntities
Content-Type: application/json
###

//Suppression
DELETE http://localhost:8081/movieEntities/2
Content-Type: application/json

###